services:
  postgres:
    image: postgres:17-alpine
    container_name: untrivial-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: untrivial
      POSTGRES_PASSWORD: untrivial-password
      POSTGRES_DB: untrivial
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
